name : Communist Cricket
brand : Communist Cricket
description : the game, the politics, the people
keyword : cricket, communism
url : communist.cricket
email : info@communist.cricket
analytics : UA-76782416-1
markdown : kramdown
permalink: pretty
exclude :
  - node_modules
