name : Communist Cricket
brand : Communist Cricket
description : the game, the politics, the people
keyword : cricket, communism
url : communist.cricket
email : info@communist.cricket
analytics :
markdown : kramdown
exclude :
  - node_modules
